# Generated by Django 4.2.11 on 2024-04-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='Movies', to='movies.actor'),
        ),
    ]
