# Generated by Django 4.2.11 on 2024-04-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='good_question',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
