# Generated by Django 4.2.11 on 2024-04-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0002_trend_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
